//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int DEPTNO { get; set; }
        public string DepName { get; set; }
        public Nullable<double> Budget { get; set; }
        public string Loc { get; set; }
    
        public virtual department department1 { get; set; }
        public virtual department department2 { get; set; }
    }
}
