#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_INJ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="infiniteDB")]
	public partial class LSQCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEMP(EMP instance);
    partial void UpdateEMP(EMP instance);
    partial void DeleteEMP(EMP instance);
    #endregion
		
		public LSQCDataContext() : 
				base(global::LINQ_INJ.Properties.Settings.Default.infiniteDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LSQCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LSQCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LSQCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LSQCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EMP> EMPs
		{
			get
			{
				return this.GetTable<EMP>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMP")]
	public partial class EMP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EMPNO;
		
		private string _ENAME;
		
		private string _JOB;
		
		private System.Nullable<int> _MGR_ID;
		
		private System.Nullable<System.DateTime> _HIREDATE;
		
		private System.Nullable<int> _SAL;
		
		private System.Nullable<int> _COMM;
		
		private System.Nullable<int> _DEPTNO;
		
		private string _remarks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMPNOChanging(int value);
    partial void OnEMPNOChanged();
    partial void OnENAMEChanging(string value);
    partial void OnENAMEChanged();
    partial void OnJOBChanging(string value);
    partial void OnJOBChanged();
    partial void OnMGR_IDChanging(System.Nullable<int> value);
    partial void OnMGR_IDChanged();
    partial void OnHIREDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnHIREDATEChanged();
    partial void OnSALChanging(System.Nullable<int> value);
    partial void OnSALChanged();
    partial void OnCOMMChanging(System.Nullable<int> value);
    partial void OnCOMMChanged();
    partial void OnDEPTNOChanging(System.Nullable<int> value);
    partial void OnDEPTNOChanged();
    partial void OnremarksChanging(string value);
    partial void OnremarksChanged();
    #endregion
		
		public EMP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPNO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EMPNO
		{
			get
			{
				return this._EMPNO;
			}
			set
			{
				if ((this._EMPNO != value))
				{
					this.OnEMPNOChanging(value);
					this.SendPropertyChanging();
					this._EMPNO = value;
					this.SendPropertyChanged("EMPNO");
					this.OnEMPNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENAME", DbType="VarChar(20)")]
		public string ENAME
		{
			get
			{
				return this._ENAME;
			}
			set
			{
				if ((this._ENAME != value))
				{
					this.OnENAMEChanging(value);
					this.SendPropertyChanging();
					this._ENAME = value;
					this.SendPropertyChanged("ENAME");
					this.OnENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB", DbType="VarChar(20)")]
		public string JOB
		{
			get
			{
				return this._JOB;
			}
			set
			{
				if ((this._JOB != value))
				{
					this.OnJOBChanging(value);
					this.SendPropertyChanging();
					this._JOB = value;
					this.SendPropertyChanged("JOB");
					this.OnJOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MGR_ID", DbType="Int")]
		public System.Nullable<int> MGR_ID
		{
			get
			{
				return this._MGR_ID;
			}
			set
			{
				if ((this._MGR_ID != value))
				{
					this.OnMGR_IDChanging(value);
					this.SendPropertyChanging();
					this._MGR_ID = value;
					this.SendPropertyChanged("MGR_ID");
					this.OnMGR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIREDATE", DbType="Date")]
		public System.Nullable<System.DateTime> HIREDATE
		{
			get
			{
				return this._HIREDATE;
			}
			set
			{
				if ((this._HIREDATE != value))
				{
					this.OnHIREDATEChanging(value);
					this.SendPropertyChanging();
					this._HIREDATE = value;
					this.SendPropertyChanged("HIREDATE");
					this.OnHIREDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAL", DbType="Int")]
		public System.Nullable<int> SAL
		{
			get
			{
				return this._SAL;
			}
			set
			{
				if ((this._SAL != value))
				{
					this.OnSALChanging(value);
					this.SendPropertyChanging();
					this._SAL = value;
					this.SendPropertyChanged("SAL");
					this.OnSALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMM", DbType="Int")]
		public System.Nullable<int> COMM
		{
			get
			{
				return this._COMM;
			}
			set
			{
				if ((this._COMM != value))
				{
					this.OnCOMMChanging(value);
					this.SendPropertyChanging();
					this._COMM = value;
					this.SendPropertyChanged("COMM");
					this.OnCOMMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPTNO", DbType="Int")]
		public System.Nullable<int> DEPTNO
		{
			get
			{
				return this._DEPTNO;
			}
			set
			{
				if ((this._DEPTNO != value))
				{
					this.OnDEPTNOChanging(value);
					this.SendPropertyChanging();
					this._DEPTNO = value;
					this.SendPropertyChanged("DEPTNO");
					this.OnDEPTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarks", DbType="NVarChar(100)")]
		public string remarks
		{
			get
			{
				return this._remarks;
			}
			set
			{
				if ((this._remarks != value))
				{
					this.OnremarksChanging(value);
					this.SendPropertyChanging();
					this._remarks = value;
					this.SendPropertyChanged("remarks");
					this.OnremarksChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
